AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/schema.rb'
    - '*file'
    - 'bin/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false
